# Generated by Django 5.1 on 2025-02-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("categories", "0001_initial"),
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Book name", max_length=64, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True, help_text="Book description", max_length=512
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="authors.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="categories.category",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Language",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
