# Generated by Django 5.0.2 on 2024-05-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chapters", "0001_initial"),
        ("groups", "0001_initial"),
        ("pages", "0001_initial"),
        ("parts", "0001_initial"),
        ("quarters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        db_index=True, default=1, help_text="Verse number"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        db_index=True, help_text="Verse text", max_length=1024
                    ),
                ),
                (
                    "transliteration",
                    models.CharField(
                        db_index=True,
                        help_text="Verse transliteration",
                        max_length=2048,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Verse chapter",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Verse group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="groups.group",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Verse page",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="pages.page",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        help_text="Verse part",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="parts.part",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        help_text="Verse quarter",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="quarters.quarter",
                    ),
                ),
            ],
            options={
                "unique_together": {("chapter", "number")},
            },
        ),
    ]
