# Generated by Django 5.1 on 2025-02-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("chapters", "0002_alter_chapter_name_alter_chapter_order_and_more"),
        ("verses", "0002_alter_verse_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(db_index=True, help_text="Item")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="books.book",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chapter",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verse",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="verses.verse",
                    ),
                ),
            ],
            options={
                "db_table": "items",
            },
        ),
    ]
