# Generated by Django 5.1 on 2025-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Chapter name", max_length=16, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="Refers to the chronological order in which the chapters of the Quran were revealed",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=1, help_text="Number of pages"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="type",
            field=models.BooleanField(
                default=True,
                help_text="Designates where the chapter is revealed True = Mecca, False = Medina",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="verse_count",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=1, help_text="Number of verses"
            ),
        ),
    ]
