# Generated by Django 5.2 on 2025-06-26 07:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_content_alter_post_created_at_and_more"),
        ("resources", "0004_alter_resource_created_at_alter_resource_updated_at"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttag",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                help_text="Tags",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_posts",
                to="blog.post",
                verbose_name="tags",
            ),
        ),
        migrations.AlterField(
            model_name="resourcetag",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                help_text="Tags",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_resources",
                to="resources.resource",
                verbose_name="tags",
            ),
        ),
    ]
