# Generated by Django 5.0.2 on 2024-05-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chapters", "0001_initial"),
        ("groups", "0001_initial"),
        ("parts", "0001_initial"),
        ("quarters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page chapter",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page group",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="groups.group",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page part",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="parts.part",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page quarter",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="quarters.quarter",
                    ),
                ),
            ],
        ),
    ]
