# Generated by Django 5.2 on 2025-04-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chapters", "0001_initial"),
        ("groups", "0001_initial"),
        ("parts", "0001_initial"),
        ("quarters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Page name", max_length=16, unique=True
                    ),
                ),
                (
                    "verse_count",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, help_text="Number of verses"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="groups.group",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        help_text="Part",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="parts.part",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="quarters.quarter",
                    ),
                ),
            ],
            options={
                "db_table": "pages",
            },
        ),
    ]
