# Generated by Django 5.0.2 on 2024-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Chapter name",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_index=True,
                        help_text="Refers to the chronological order in which the chapters of the Quran were revealed.",
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.BooleanField(
                        default=True,
                        help_text="Designates where the chapter is revealed, True means the chapter revealed in Mecca. False means the chapter revealed in Medina",
                    ),
                ),
                (
                    "verse_count",
                    models.IntegerField(
                        db_index=True, help_text="Number of verses of the chapter"
                    ),
                ),
                (
                    "translation",
                    models.CharField(
                        db_index=True,
                        help_text="Chapter translation",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "transliteration",
                    models.CharField(
                        db_index=True,
                        help_text="Chapter transliteration",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
            ],
        ),
    ]
