# Generated by Django 5.2 on 2025-04-28 09:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Amiri", "Amiri"),
                            ("font-kufam", "Kufam"),
                            ("font-fustat", "Fustat"),
                            ("font-reem", "Reem Kufi"),
                            ("font-almarai", "Almarai"),
                            ("font-cairo", "Cairo Play"),
                            ("Amiri Quran", "Amiri Quran"),
                            ("font-kufi", "Noto Kufi Arabic"),
                            ("font-reem-fun", "Reem Kufi Fun"),
                            ("font-noto-ar", "Noto Sans Arabic"),
                        ],
                        help_text="Quran Font",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("light", "Light"),
                            ("silk", "Light (Silk)"),
                            ("lofi", "Light (Simple)"),
                            ("caramellatte", "Light (Gold)"),
                            ("cupcake", "Light (Lightblue)"),
                            ("winter", "Light (Blue)"),
                            ("dark", "Dark"),
                            ("dim", "Dark (Simple)"),
                            ("luxury", "Dark (Gold)"),
                            ("night", "Dark (Lightblue)"),
                            ("forest", "Dark (Green)"),
                            ("sunset", "Dark (Orange)"),
                        ],
                        help_text="App Theme",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "interpretation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quran interpretation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interpretations",
                        to="collections.collection",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quran translation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations",
                        to="collections.collection",
                    ),
                ),
                (
                    "transliteration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quran transliteration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transliterations",
                        to="collections.collection",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
