# Generated by Django 5.1.7 on 2025-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="font",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Amiri", "Amiri"),
                    ("font-kufam", "Kufam"),
                    ("font-fustat", "Fustat"),
                    ("font-reem", "Reem Kufi"),
                    ("font-almarai", "Almarai"),
                    ("font-cairo", "Cairo Play"),
                    ("Amiri Quran", "Amiri Quran"),
                    ("font-kufi", "Noto Kufi Arabic"),
                    ("font-reem-fun", "Reem Kufi Fun"),
                    ("font-noto-ar", "Noto Sans Arabic"),
                ],
                help_text="Quran Font",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light", "Light"),
                    ("silk", "Light (Silk)"),
                    ("lofi", "Light (Simple)"),
                    ("caramellatte", "Light (Gold)"),
                    ("cupcake", "Light (Lightblue)"),
                    ("winter", "Light (Blue)"),
                    ("dark", "Dark"),
                    ("dim", "Dark (Simple)"),
                    ("luxury", "Dark (Gold)"),
                    ("night", "Dark (Lightblue)"),
                    ("forest", "Dark (Green)"),
                    ("sunset", "Dark (Orange)"),
                ],
                help_text="App Theme",
                max_length=16,
                null=True,
            ),
        ),
    ]
