# Generated by Django 5.1 on 2025-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="content",
            field=models.CharField(
                db_index=True, help_text="Verse content", max_length=1024
            ),
        ),
    ]
