# Generated by Django 5.2 on 2025-06-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0003_alter_chapter_created_at_alter_chapter_name_and_more"),
        ("collections", "0002_alter_collection_created_at_and_more"),
        ("items", "0001_initial"),
        ("verses", "0002_alter_verse_chapter_alter_verse_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                help_text="Item chapter",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="chapters.chapter",
                verbose_name="chapter",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="collection",
            field=models.ForeignKey(
                help_text="Item collection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="collections.collection",
                verbose_name="collection",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="content",
            field=models.TextField(
                db_index=True, help_text="Item content", verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="verse",
            field=models.ForeignKey(
                blank=True,
                help_text="Item verse",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="verses.verse",
                verbose_name="verse",
            ),
        ),
    ]
