# Generated by Django 5.2 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Part name",
                max_length=16,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Number of pages",
                verbose_name="page count",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="verse_count",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Number of verses",
                verbose_name="verse count",
            ),
        ),
    ]
