# Generated by Django 5.2 on 2025-06-26 07:45

import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_content"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("code", 4),
                    ("image", 5),
                    ("document", 6),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Paragraph"}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 2), ("code", 3)]],
                        {"help_text": "Code"},
                    ),
                    5: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Blog content",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="headline",
            field=models.CharField(
                db_index=True,
                help_text="Blog headline",
                max_length=128,
                verbose_name="headline",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Post tags",
                through="tags.PostTag",
                to="taggit.Tag",
                verbose_name="tags",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
    ]
