# Generated by Django 5.1 on 2024-11-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chapters", "0001_initial"),
        ("languages", "0001_initial"),
        ("verses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(db_index=True, help_text="Translation")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chapter",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Language",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="languages.language",
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verse",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="verses.verse",
                    ),
                ),
            ],
            options={
                "db_table": "translations",
            },
        ),
    ]
