# Generated by Django 5.2 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Language code",
                max_length=8,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Language name",
                max_length=32,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
    ]
