# Generated by Django 5.1 on 2024-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Part name", max_length=32, unique=True
                    ),
                ),
                (
                    "verse_count",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Number of verses of the chapter",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
            ],
            options={
                "db_table": "parts",
            },
        ),
    ]
