# Generated by Django 5.2 on 2025-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Chapter name",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Refers to the chronological order in which the chapters of the Quran were revealed",
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.BooleanField(
                        default=True,
                        help_text="Designates where the chapter is revealed True = Mecca, False = Medina",
                    ),
                ),
                (
                    "verse_count",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, help_text="Number of verses"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, help_text="Number of pages"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
            ],
            options={
                "db_table": "chapters",
            },
        ),
    ]
