# Generated by Django 5.2 on 2025-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="type",
            field=models.BooleanField(
                choices=[(True, "Meccan"), (False, "Meccan")],
                default=True,
                help_text="Designates where the chapter is revealed",
            ),
        ),
    ]
