# Generated by Django 5.2 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0002_alter_chapter_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Chapter name",
                max_length=16,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="Chronological order in which chapters were revealed",
                unique=True,
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Number of pages",
                verbose_name="page count",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="type",
            field=models.BooleanField(
                choices=[(True, "Meccan"), (False, "Medinan")],
                default=True,
                help_text="Designates where the chapter is revealed",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="verse_count",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Number of verses",
                verbose_name="verse count",
            ),
        ),
    ]
