# Generated by Django 5.2 on 2025-06-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Quarter name",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "verse_count",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, help_text="Number of verses"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, help_text="Number of pages"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarters",
                        to="groups.group",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        help_text="Part",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarters",
                        to="parts.part",
                    ),
                ),
            ],
            options={
                "db_table": "quarters",
            },
        ),
    ]
