# Generated by Django 5.2 on 2025-06-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_created_at_alter_group_name_and_more"),
        ("parts", "0002_alter_part_created_at_alter_part_name_and_more"),
        ("quarters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quarter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="group",
            field=models.ForeignKey(
                help_text="Quarter group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quarters",
                to="groups.group",
                verbose_name="group",
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Quarter name",
                max_length=16,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Number of pages",
                verbose_name="page count",
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="part",
            field=models.ForeignKey(
                help_text="Quarter part",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quarters",
                to="parts.part",
                verbose_name="part",
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="verse_count",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Number of verses",
                verbose_name="verse count",
            ),
        ),
    ]
