# Generated by Django 5.1.7 on 2025-04-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Translation"),
                            (1, "Transliteration"),
                            (2, "Interpretation"),
                            (4, "Recitation"),
                        ],
                        default=0,
                        help_text="Collection type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Collection name",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True,
                        help_text="Collection description",
                        max_length=512,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Language",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "db_table": "collections",
            },
        ),
    ]
