# Generated by Django 5.2 on 2025-06-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
        ("languages", "0002_alter_language_code_alter_language_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.CharField(
                db_index=True,
                help_text="Collection description",
                max_length=512,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="language",
            field=models.ForeignKey(
                help_text="Collection Language",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="languages.language",
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Collection name",
                max_length=64,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Translation"),
                    (1, "Transliteration"),
                    (2, "Interpretation"),
                    (4, "Recitation"),
                ],
                default=0,
                help_text="Collection type",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
    ]
