# Generated by Django 5.2 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_remove_resource_tags_alter_resource_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
    ]
