# Generated by Django 5.2 on 2025-06-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0003_alter_chapter_created_at_alter_chapter_name_and_more"),
        ("groups", "0002_alter_group_created_at_alter_group_name_and_more"),
        ("pages", "0002_alter_page_chapter_alter_page_created_at_and_more"),
        ("parts", "0002_alter_part_created_at_alter_part_name_and_more"),
        ("quarters", "0002_alter_quarter_created_at_alter_quarter_group_and_more"),
        ("verses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="chapter",
            field=models.ForeignKey(
                help_text="Verse chapter",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verses",
                to="chapters.chapter",
                verbose_name="chapter",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="content",
            field=models.CharField(
                db_index=True,
                help_text="Verse content",
                max_length=1024,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date created", verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="group",
            field=models.ForeignKey(
                help_text="Verse group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verses",
                to="groups.group",
                verbose_name="group",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="number",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Verse number",
                verbose_name="number",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="page",
            field=models.ForeignKey(
                help_text="Verse page",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verses",
                to="pages.page",
                verbose_name="page",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="part",
            field=models.ForeignKey(
                help_text="Verse part",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verses",
                to="parts.part",
                verbose_name="part",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="quarter",
            field=models.ForeignKey(
                help_text="Verse quarter",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verses",
                to="quarters.quarter",
                verbose_name="quarter",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update", verbose_name="Last update"
            ),
        ),
    ]
